
-----------------------------------------------------------------------
---- Automatically generated by generate_premake.py. Do not edit ! ----
-----------------------------------------------------------------------

project("libavformat")
  uuid("CC02A970-0085-4EE7-BA9B-D4CCCD9C1F6E")
  kind("StaticLib")
  language("C")
  ffmpeg_common()
  filter({"platforms:Windows-x86_64"})
    buildoptions({ "/FIconfig_windows_x86_64.h" })
  filter({"platforms:Windows-ARM64"})
    buildoptions({ "/FIconfig_windows_aarch64.h" })
  filter({"platforms:Windows", "architecture:x86_64"})
    buildoptions({ "/FIconfig_windows_x86_64.h" })
  filter({"platforms:Windows", "architecture:ARM64"})
    buildoptions({ "/FIconfig_windows_aarch64.h" })
  filter({"platforms:Linux-x86_64"})
    buildoptions({ "-include config_linux_x86_64.h" })
  filter({"platforms:Linux-ARM64"})
    buildoptions({ "-include config_linux_aarch64.h" })
  filter({"platforms:Mac-x86_64"})
    buildoptions({ "-include config_macos_x86_64.h" })
  filter({"platforms:Mac-ARM64"})
    buildoptions({ "-include config_macos_aarch64.h" })
  filter({"platforms:Android-x86_64"})
    buildoptions({ "-include config_android_x86_64.h" })
  filter({"platforms:Android-ARM64"})
    buildoptions({ "-include config_android_aarch64.h" })
  filter({})

  filter("files:not wmaprodec.c")
    warnings "Off"
  filter({})

  links({
    "libavcodec",
    "libavutil",
  })

  -- libavformat/Makefile:
  --   HEADERS:
  files({
    "avformat.h",
    "avio.h",
    "version.h",
  })
  --   OBJS:
  files({
    "allformats.c",
    "avio.c",
    "aviobuf.c",
    "dump.c",
    "format.c",
    "id3v1.c",
    "id3v2.c",
    "metadata.c",
    "mux.c",
    "options.c",
    "os_support.c",
    "protocols.c",
    "riff.c",
    "sdp.c",
    "url.c",
    "utils.c",
  })
  filter({"platforms:Windows or platforms:Windows-ARM64 or platforms:Windows-x86_64"})
  files({
    "file_open.c",
  })
  filter({"platforms:Mac-ARM64 or platforms:Mac-x86_64"})
  files({
    "network.c",
    "riffdec.c",
    "wavdec.c",
    "pcm.c",
  })
  filter({})
